from setuptools import setup, find_packages

setup(
    name="lightemma",
    version="0.1.0",
    description="Lightweight End-to-end Multimodal Autonomous Driving Framework",
    long_description=open("readme.md", "r").read(),
    long_description_content_type="text/markdown",
    author="LightEMMA Team",
    author_email="haoweili@umich.edu",
    url="https://github.com/QZJGeorge/Light-Emma",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "anthropic==0.49.0",
        "descartes==1.1.0",
        "einops==0.8.1",
        "fire==0.7.0",
        "google-generativeai==0.8.4",
        "huggingface-hub==0.29.3",
        "joblib==1.4.2",
        "matplotlib==3.5.3",
        "numpy==1.26.4",
        "nuscenes-devkit==1.1.11",
        "openai==0.28.0",
        "opencv-python==4.11.0.86",
        "pandas==2.2.3",
        "pillow==11.1.0",
        "pycocotools==2.0.8",
        "pyquaternion==0.9.9",
        "pyyaml==6.0.2",
        "qwen-vl-utils==0.0.10",
        "scikit-learn==1.6.1",
        "scipy==1.15.2",
        "shapely==1.8.5.post1",
        "tabulate==0.9.0",
        "timm==1.0.15",
        "tokenizers==0.21.1",
        "torch==2.6.0",
        "torchvision==0.21.0",
        "tqdm==4.67.1",
        "transformers==4.49.0",
        "xformers==0.0.29.post3",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
    ],
    entry_points={
        "console_scripts": [
            "lightemma-predict=predict_vlm:run_prediction",
            "lightemma-eval=evaluate_single:main",
            "lightemma-baseline=evaluate_baseline:main",
            "lightemma-compare=evaluate_all:main",
        ],
    },
)